### PR TITLE
More in-depth & beginner friendly noise explanations

### PR DESCRIPTION
**Pull request by Astrashh**

### CODE REVIEW

**Comment by Astrashh** [comment]
###### Hierarchy of non-esoteric noise functions

These categories should be included in the main noise page.
Each level should be provided with explanation such that readers can build up an internal model of the different categories, including how they differ, unique characteristics, and examples of general applications. There should however not be in-depth technical explanations, as they will be delegated to external pages (especially cellular).
```
coherent
  gradient
    simplex
      perlin
      simplex
      opensimplex2
      opensimplex2s
    gabor
  value
    value
    value (cubically interpolated)
  cellular
random
  white noise
  gaussian noise
  ```

**Comment by dfsek** [comment]
Some explanations of random things that I wrote up during class: :sunglasses: 

## Important Terms

### Isotropic
Isotropy is the property of having uniform properties in all directions. Anisotropy is the lack of isotropy. All noise functions included in Terra are isotropic by default, though some (such as Gabor noise) can be made anisotropic with the `isotropic` option disabled, and any noise function can be made anisotropic through various means with the `Expression` sampler. 
#### Anisotropic
anisotropic noise
#### Isotropic
isotropic noise


I will continue to edit this comment whenever I find time.

**Comment by Astrashh** [comment]
Might expand the noise page or create a secondary page with misc information such as isotropy / anisotropy in a second PR, but for now this will do.

**Comment by Astrashh** [comment]
The categorization of available noise functions will also be handled on a separate page in another PR.

**Review by dfsek — APPROVED** [review]

**Pull request merged**
